name: yt_playlists_plus
description: A new Flutter project.
publish_to: 'none'
version: 1.0.6

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  timeago: ^3.5.0
  window_manager: ^0.3.6
  youtube_explode_dart: ^1.12.4
#   flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons:
#   image_path_android: "assets/icon/app_icon.png"
#   android: true
#   web:
#     generate: true
#     image_path: "assets/icon/app_icon.png"
#   windows:
#     generate: true
#     image_path: "assets/icon/app_icon.png"

#? uncomment the above and run:
#? flutter pub run flutter_launcher_icons
#? to generate new icons


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/no-thumbnail.png
